Repository toobigtoignore/issf, pull requests merged in 2018-12, with the labels that each got.

#37 Update .gitattributes to hide psql from linguist.
  .gitattributes
Labels: enhancement, low priority

#41 Merge dev branch changes to fix .gitattribues
  .gitattributes
Labels: enhancement, low priority, meta

#43 Delete container_development.rst from root directory
  container_development.rst
Labels: meta

#46 Tidied up the scripts in the scripts directory
  scripts/db_shell.sh
  scripts/issf_shell.sh
  scripts/npm.sh
  scripts/postgres_clean_db.sh
  scripts/server/provision.sh
Labels: low priority, meta

#94 Cleaned up /apps/frontend
  apps/details/views.py
  apps/frontend/forms.py
  apps/frontend/urls.py
  apps/frontend/views.py
Labels: enhancement, low priority, python

#101 Fixed error related to trying to focus non-existent field
  apps/issf_base/models.py
Labels: bug, python, urgent

#110 Blacklisted brackets from being used in the search
  apps/frontend/views.py
Labels: bug, python

#134 Fixed national geographic scope not saving
  apps/details/forms.py
  apps/details/views.py
Labels: backend, bug, urgent

#130 Hide Global and Not specific SSFs from the map
  apps/frontend/templates/frontend/index.html
  apps/frontend/views.py
Labels: bug, frontend, urgent

#136 Fixed missing whitespace in recent contributions by country block on index
  apps/frontend/templates/frontend/index.html
Labels: bug, frontend, low priority

#133 Fix end year not being saved
  apps/details/templates/details/contribute.html
  apps/details/templates/details/ssfprofile_details.html
  apps/details/views.py
  apps/issf_base/models.py
Labels: backend, bug, frontend

#165 Various Choropleth Layer Fixes
  apps/frontend/templates/frontend/index.html
  static_root/frontend/css/frontend.css
  static_root/frontend/js/chorodata.json
  static_root/js/chorodata.json
Labels: frontend

#157 Cleaned up the backend more and resolved issue #152
  apps/details/forms.py
  apps/details/urls.py
  apps/details/views.py
  apps/issf_admin/views.py
  apps/issf_base/models.py
Labels: backend, bug, enhancement, medium priority

#192 Fix TypeError preventing logout
  apps/issf_admin/views.py
  apps/issf_base/templates/issf_base/base.html
  issf_prod/urls.py
Labels: backend, frontend, medium priority

#194 Made front-page report link go to a pdf report rather than the now hidden webpage report
  apps/frontend/templates/frontend/index.html
Labels: enhancement, frontend, low priority

#196 Made docker_nuke be slightly more precise, to reduce the amount of collateral damage
  scripts/docker_nuke.sh
Labels: backend, enhancement, low priority, meta

#199 Fixed TemplateSyntaxError when attempting to load changelog page
  apps/details/templates/details/changelog.html
Labels: bug, frontend, low priority

#202 Fixed the sitemap
  apps/details/views.py
  apps/issf_admin/views.py
  apps/issf_base/models.py
  apps/issf_base/utils.py
  issf_prod/settings.py
  issf_prod/urls.py
Labels: backend, bug, enhancement, medium priority

#205 Document backend
  apps/details/admin.py
  apps/details/forms.py
  apps/details/views.py
  apps/frontend/forms.py
  apps/frontend/views.py
  apps/issf_admin/forms.py
  apps/issf_admin/models.py
  apps/issf_admin/views.py
  apps/issf_base/models.py
  apps/issf_base/utils.py
  issf_prod/settings.py
Labels: backend, enhancement, low priority, meta

#207 Fixed error with type hinting, as well as being able to create faq entries while not staff
  apps/details/views.py
  apps/frontend/views.py
Labels: backend, bug, enhancement, urgent

#210 Moved report-generation scripts into the scripts folder
  scripts/reports/contributions_by_country_incl_global_ns.sql
  scripts/reports/contributions_by_geog_scope.sql
  scripts/reports/contributions_by_record_type.sql
  scripts/reports/monthly_contributions.sql
  scripts/reports/monthly_contributions_by_geographic_scope_type.sql
  scripts/reports/monthly_contributions_by_record_type.sql
  scripts/reports/monthly_contributions_by_topx_country.sql
Labels: enhancement, low priority, meta

#208 Fixed tweet checkboxes appearing in places that they shouldn't
  apps/details/forms.py
  apps/details/templates/details/contribute.html
  apps/details/views.py
Labels: backend, enhancement, frontend, medium priority

#211 Added script to automatically run collect static on file change
  scripts/web_collectstatic.sh
Labels: enhancement, low priority, meta

#209 Rewrite search
  apps/details/forms.py
  apps/details/templates/details/ssf_case_study_details.html
  apps/details/templates/details/ssfcapacity_details.html
  apps/details/templates/details/ssfexperiences_details.html
  apps/details/templates/details/ssfguidelines_details.html
  apps/details/templates/details/ssfknowledge_details.html
  apps/details/templates/details/ssforganization_details.html
  apps/details/templates/details/ssfperson_details.html
  apps/details/templates/details/ssfprofile_details.html
  apps/frontend/forms.py
  apps/frontend/templates/frontend/index.html
  apps/frontend/views.py
  apps/issf_admin/forms.py
  apps/issf_base/models.py
  static_root/css/frontend.css
  static_root/frontend/css/frontend.css
  static_root/issf_base/issf-css/main.css
Labels: backend, enhancement, frontend, urgent

#216 Fixed error with updating user profile
  static_root/details/js/error-handling.js
Labels: bug, frontend, medium priority

#217 Fixed line under map title
  static_root/issf_base/issf-css/main.css
Labels: bug

#214 Reverted to old sidebar functionality
  apps/frontend/templates/frontend/index.html
Labels: urgent

#221 Removed Jack's broken placeholder
  apps/frontend/forms.py
Labels: backend, bug, urgent

#225 v2 of ✓✓✓✓✓
  apps/frontend/templates/frontend/index.html
  static_root/issf_base/issf-css/main.css
Labels: frontend
