Repository toobigtoignore/issf, pull requests merged in 2019-01, with the labels that each got.

#227 Index cosmetic
  apps/frontend/templates/frontend/index.html
  static_root/issf_base/issf-css/main.css
Labels: frontend

#232 Removed desktop.ini
  .gitignore
  assets/images/desktop.ini
Labels: bug, meta

#233 Fixed internal server error when trying to generate a pdf report for a regional record
  apps/details/views.py
  apps/issf_base/models.py
Labels: backend, bug, urgent
